name: Build and Tests
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build solution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build projects
        run: |
          dotnet build Training.sln

      - name: run unit tests
        run: |
          dotnet test Training.sln --results-directory TestResults --collect:"XPlat Code Coverage"

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "TestResults/**/*.xml"
        if: always()
        
          
          

